//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonicaDatos.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class telefonos
    {
        public int Numero { get; set; }
        public Nullable<short> Territorio { get; set; }
        public string Estado { get; set; }
        public string Observaciones { get; set; }
    }
}
